### ISSUE TITLE
执行测试后，代码仍然显示未覆盖

### ISSUE THREAD

**Issue by zhongx** [didi/super-jacoco#37]
1）修改数据库和git信息，启动 super-jacoco，默认端口8899

2）启动测试程序demo，demo的端口是8080，tcpserver的端口是18513
java -javaagent:/Users/org.jacoco.agent-0.8.5-runtime.jar=includes=*,output=tcpserver,address=127.0.0.1,port=18513,append=false -jar /Users/demo-0.0.1-SNAPSHOT.jar

3）执行测试 ，postman调用demo的增量方法： http://127.0.0.1:8080/brand/listAll2

4）收集覆盖率文件
post，type=2为增量，port传的是第2步的tcpserver的端口
http://127.0.0.1:8899/cov/triggerEnvCov
{
    "uuid": "0001",
    "type": 2, 
    "gitUrl": "http://****/demo.git",
    "subModule": "",
    "baseVersion": "release-0001",
    "nowVersion": "release-0002",
    "address": "127.0.0.1",
    "port": "18513"
}

5）获取覆盖率结果
get
http://127.0.0.1:8899/cov/triggerEnvCov?uuid=0001

非常奇怪的是，增量的代码依然显示红色，明明已经postman执行了。
请教各位大佬，看看哪里出问题了。非常感谢！！

**Comment by zhongx** [comment]
.

**Comment by zhongx** [comment]
1

**Comment by scofier** [comment]
问题解决了吗

**Comment by ilaotan** [comment]
3）执行测试 ，postman调用demo的增量方法： http://127.0.0.1:8080/brand/listAll2
这一步骤是什么鬼？  jacoco是单元测试覆盖率呀，还能用postman测？

**Comment by flyletc** [comment]
您好，问题解决了吗，我也遇到了类似的问题
