### ISSUE TITLE
在获取报告时，为何要向 /cov/triggerUnitCover 进行传参？

### ISSUE THREAD

**Issue by Awesome93** [didi/super-jacoco#7]
我已经完成了将 Jacoco 在服务器上的集成，走通了流程，并获取了一份完整的测试报告。

但我在使用 super-jacoco 时碰到了一些问题，我详细阅读了许多遍文档，但依然没能找到解决办法。

现将问题列在下方，希望能得到帮助，谢谢！

1、使用super-jacoco时，是否仍然需要在项目的 JVM 中添加 -javaagent 的启动参数？

2、Readme.md 文档中写道 「需要在 application.properties 中更改 spring.datasource.url、spring.datasource.username、spring.datasource.password」这三个字段。请问这三个字段是否就是「后台服务所连接的数据库」？

3、如果成功使用 super-jacoco 执行了测试，在获取报告阶段，向类似「 /cov/triggerUnitCover 」这个 URL 传参的目的是什么？
因为我在原始的 Jacoco 使用文档中并未看到向接口传参的操作。

**Comment by xiaoyisss** [comment]
1、需要的；
2、这个是指super-jacoco需要用的数据库（对应建表sql已在sql目录下）；
3、triggerUnitCover这个接口是触发单元测试覆盖率的接口，传参的目的看readme4.1

**Comment by Awesome93** [comment]
> 1、需要的；
> 2、这个是指super-jacoco需要用的数据库（对应建表sql已在sql目录下）；
> 3、triggerUnitCover这个接口是触发单元测试覆盖率的接口，传参的目的看readme4.1

@xiaoyisss 在向 /cov/triggerUnitCover 传参时，前面补齐的 IP 地址后面需要加端口号么“
比如，是否需要向形如：
http://192.168.1.1:0000/cov/triggerUnitCover
这个 URL 传参，还是向形如：
http://192.168.1.1/cov/triggerUnitCover
传参即可？

如果需要加端口号的话，应该加哪一个端口号呢？
